[project]
name = "profiling-project"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "kafka-python>=2.2.15",
    "kubernetes>=32.0.0",
    "memray>=1.18.0",
    "nvidia-ml-py>=13.580.82",
    "psutil>=7.0.0",
    "psycopg2-binary>=2.9.10",
]
