role: "Aggregator"

env:
  - name: PG_USER
    valueFrom:
      secretKeyRef:
        name: db-credentials
        key: PG_USER
  - name: PG_DBNAME
    value: "postgres"
  - name: PG_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-credentials
        key: PG_PASSWORD

customConfig:
  sources:
    kafka_source:
      type: "kafka"
      bootstrap_servers: "my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
      topics: ["performance-metrics"]
      group_id: "vector-loki-sink"
      decoding:
        codec: "json"

  sinks:
    loki_sink:
      type: "loki"
      endpoint: "http://lgtm-loki-gateway.lgtm.svc.cluster.local:80"
      inputs: ["kafka_source"]
      labels:
        job: '{{ printf "{{ step_name }}" }}'
        run_id: '{{ printf "{{ run_id }}" }}'
        namespace: '{{ printf "{{ namespace }}" }}'
      encoding:
        codec: "json"

    timescaledb_sink:
      type: "postgres"
      inputs: ["kafka_source"] # Takes input from the same Kafka source
      endpoint: "postgres://${PG_USER}:${PG_PASSWORD}@timescaledb.timescale.svc.cluster.local:5450/${PG_DBNAME}"
      table: "performance_metrics"

service:
  enabled: true
  type: "ClusterIP"
  topologyKeys: ["*"]
  ports:
    - name: http
      port: 8686
      targetPort: 80
