apiVersion: batch/v1
kind: Job
metadata:
  # Using a fixed name instead of generateName
  name: python-logger-job
spec:
  template:
    spec:
      containers:
        - name: logger-app
          image: python-logger-app:latest
          imagePullPolicy: Never
          env:
            - name: PG_HOST
              value: "timescaledb.timescale"
            - name: PG_PORT
              value: "5450"
            - name: PG_DBNAME
              value: "postgres"

            # Since the name is static, we create a unique ID inside the pod.
            # The pod gets a unique name from the Job controller.
            - name: RUN_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: PG_USER
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: PG_PASSWORD
      restartPolicy: OnFailure
  # This automatically cleans up the Job and Pod 10 minutes after it finishes.
  ttlSecondsAfterFinished: 600
