apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: performance-metrics
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 2
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
